on:
  push:
    branches:
    - main
    - release/*

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - name: cache
        uses: actions/cache@v5.0.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: /tmp
          # An explicit key for restoring and saving the cache
          key: 123
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.

      - name: Print1
        run: |
          echo "$ACTIONS_CACHE_URL"
          
      - name: Print2
        run: env 



